// Generated from PROMTHEUS CHATBOT TRAINING PDFs. Do not edit by hand.
export type PrometheusKnowledgeChunk = {
  id: string
  source: string
  title: string
  chunkIndex: number
  content: string
  tags: string[]
}

export const PROMETHEUS_KNOWLEDGE_CHUNKS = [
  {
    "id": "doc1-chunk1",
    "source": "01_prometheus_system_overview.pdf",
    "title": "01 Prometheus System Overview",
    "chunkIndex": 1,
    "content": "PROMETHEUS AUTOMATED VIDEO EDITING SYSTEM KNOWLEDGE BASE 1. SYSTEM OVER VIEW Prometheus is an intelligent, automated video editing orchestration system designed to streamline postproduction workflows through AI-assisted decision making, automated asset management, and contextaware editing suggestions. It operates as a hybrid human-in-the-loop automation platform where the AI handles repetitive, technical, and time-consuming tasks while preserving creative control for the human editor. 1.1 Core Philosophy \u2022 Automation First, Creative Second : Handle cuts, sync, color matching, and format conversion automatically. Reserve human judgment for creative decisions, pacing, and emotional beats. \u2022 Context Preservation : Every edit decision must maintain awareness of the full project context - source footage properties, delivery specifications, target platform, and narrative intent. \u2022 Non-Destructive W orkflow: All automated operations generate new render passes or metadata layers; original source media is never altered. \u2022 Progressive Disclosure : Surface only relevant options to the user based on current project state. Do not overwhelm beginners with advanced features; do not constrain experts with oversimplified defaults. 1.2 System Architecture Input Layer : Ingests raw footage, audio, graphics, project files (Premiere, DaVinci, Final Cut), and metadata (XML, EDL, CSV markers). Analysis Engine : \u2022 Scene detection and shot",
    "tags": [
      "prometheus",
      "system",
      "overview"
    ]
  },
  {
    "id": "doc1-chunk2",
    "source": "01_prometheus_system_overview.pdf",
    "title": "01 Prometheus System Overview",
    "chunkIndex": 2,
    "content": "nput Layer : Ingests raw footage, audio, graphics, project files (Premiere, DaVinci, Final Cut), and metadata (XML, EDL, CSV markers). Analysis Engine : \u2022 Scene detection and shot classification (wide, medium, close-up, insert) \u2022 Audio analysis (dialogue vs. music vs. SFX, loudness profiling, transcription) \u2022 Visual analysis (lighting conditions, camera movement, focus quality, color temperature) \u2022 Content analysis (face detection, object recognition, text-on-screen detection) Decision Engine : \u2022 Rule-based heuristics for technical corrections (sync, levels, format compliance) \u2022 ML-based ranking for creative suggestions (cut points, transition selection, music alignment) \u2022 User preference learning that adapts suggestion rankings based on accepted/rejected recommendations Execution Layer : \u2022 Automated proxy generation and timeline assembly \u2022 Render queue management with platform-specific preset application \u2022 Export validation (checksum verification, spec compliance testing) F eedback Loop: Generated by Kimi.ai \u2022 User corrections are logged as training signals \u2022 A/B testing framework for suggestion algorithms \u2022 Performance metrics (time saved, rejection rate, render success rate) 2. KEY CAPABILITIES & TOOLS 2.1 Automated Sync & Assembly \u2022 Multi-cam Sync : Synchronizes footage using audio waveforms, timecode, or visual markers. Handles drift correction for long-form recordings. \u2022 Assembly Cut Generation : Creates rough cuts",
    "tags": [
      "prometheus",
      "system",
      "overview"
    ]
  },
  {
    "id": "doc1-chunk3",
    "source": "01_prometheus_system_overview.pdf",
    "title": "01 Prometheus System Overview",
    "chunkIndex": 3,
    "content": "m Sync : Synchronizes footage using audio waveforms, timecode, or visual markers. Handles drift correction for long-form recordings. \u2022 Assembly Cut Generation : Creates rough cuts based on script/transcript alignment, speaker detection, and scene boundaries. \u2022 B-roll Insertion : Automatically identifies relevant B-roll from a media pool based on spoken keywords and contextual relevance scoring. 2.2 Smart Color & Audio \u2022 Color Matching : Applies LUTs and primary corrections to unify footage from different cameras or lighting conditions. Maintains skin tone protection. \u2022 Audio Sweetening : Normalizes dialogue to -23 LUFS (broadcast) or -16 LUFS (web), applies dynamic EQ, and ducking music under speech. \u2022 Noise Reduction : Adaptive spectral noise reduction for location audio without dialogue degradation. 2.3 Platform Optimization \u2022 Multi-format Export : Simultaneous generation of deliverables - 4K ProRes 422 HQ for archive, 1080p H.264 for review, vertical 9:16 H.265 for social. \u2022 Caption Generation : Automated transcription with speaker labeling, punctuation restoration, and burn-in or SRT/VTT export. \u2022 Thumbnail Extraction : Identifies visually compelling frames using composition scoring (rule of thirds, face prominence, motion blur avoidance). 2.4 Quality Assurance \u2022 T echnical QC: Detects flash frames, audio dropouts, black frames, resolution mismatches, and frame rate inconsistencies. \u2022 Compliance Checking : Validates",
    "tags": [
      "prometheus",
      "system",
      "overview"
    ]
  },
  {
    "id": "doc1-chunk4",
    "source": "01_prometheus_system_overview.pdf",
    "title": "01 Prometheus System Overview",
    "chunkIndex": 4,
    "content": "2.4 Quality Assurance \u2022 T echnical QC: Detects flash frames, audio dropouts, black frames, resolution mismatches, and frame rate inconsistencies. \u2022 Compliance Checking : Validates against broadcast safe levels (luma, chroma, audio peaks), platform-specific duration limits, and aspect ratio requirements. \u2022 Render V erification: Frame-by-frame checksum comparison between source and output to catch encoding artifacts. 3. INTEGRATION POINTS Prometheus is designed to augment existing workflows rather than replace them: \u2022 NLE Plugins : Deep integration with Adobe Premiere Pro, DaVinci Resolve, and Final Cut Pro via extension panels \u2022 Cloud Storage : Native support for Frame.io, Dropbox, Google Drive, A WS S3, and Azure Blob for proxy streaming and asset retrieval Generated by Kimi.ai \u2022 Asset Libraries : Connection to stock footage providers (Artgrid, Storyblocks), music licensing (Epidemic Sound, Artlist), and font libraries \u2022 Project Management : Slack/Discord notifications, Trello/Asana task creation, and Notion documentation generation 4. USER PERSONAS & WORKFLOWS 4.1 Solo Creator (Y ouT uber, F reelancer) Needs: Speed, simplicity, one-click optimization for multiple platforms Workflow: Upload -> Auto-sync -> Auto-cut -> Review suggestions -> Export all formats -> Publish 4.2 Production House (Agency , Studio) Needs: Consistency across editors, brand compliance, collaborative review, version control Workflow: Ingest ->",
    "tags": [
      "prometheus",
      "system",
      "overview"
    ]
  },
  {
    "id": "doc1-chunk5",
    "source": "01_prometheus_system_overview.pdf",
    "title": "01 Prometheus System Overview",
    "chunkIndex": 5,
    "content": "Export all formats -> Publish 4.2 Production House (Agency , Studio) Needs: Consistency across editors, brand compliance, collaborative review, version control Workflow: Ingest -> Auto-assembly -> Color pass -> Audio pass -> Client review link -> Revision tracking -> Final delivery 4.3 Live/Event Producer Needs: Rapid turnaround, multi-cam management, live-to-tape editing, social clip extraction Workflow: Live ingest -> Real-time sync -> Highlight detection -> Auto-assembly -> Platform-specific export within 30 minutes of event end 5. PERFORMANCE METRICS & SUCCESS CRITERIA \u2022 Time Reduction : Target 60-80% reduction in assembly and technical correction time \u2022 Accuracy: Sync accuracy >99.5%, transcription accuracy >95%, color matching perceptual score >4.5/5 \u2022 User Satisfaction : Suggestion acceptance rate >70%, rejection rate <20%, manual override rate <10% \u2022 Render Success : >99.9% successful first-pass renders without encoding failures END OF PROMETHEUS SYSTEM OVER VIEW DOCUMENT Generated by Kimi.ai",
    "tags": [
      "prometheus",
      "system",
      "overview"
    ]
  },
  {
    "id": "doc2-chunk1",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 1,
    "content": "VIDEO EDITING BEST PRACTICES - PROMETHEUS KNOWLEDGE BASE 1. FUNDAMENTAL EDITING PRINCIPLES 1.1 The Invisible Edit The best edit is the one the audience never notices. Every cut should serve the narrative or maintain visual continuity. Prometheus prioritizes edits that: \u2022 Preserve eye-line continuity across shots \u2022 Maintain consistent screen direction (180-degree rule) \u2022 Cut on action (motion motivates the transition) \u2022 A void jump cuts on static subjects unless stylistically intentional 1.2 Pacing & Rhythm Pacing is determined by shot duration, not just cut frequency: \u2022 Dialogue scenes : Hold on speaker for 2-3 seconds after line delivery to let emotional beats land. Cut to listener reaction before cutting back. \u2022 Action sequences : Cut on impacts, use shorter durations (0.5-2 seconds), vary shot scale to maintain energy. \u2022 Montage sequences : Accelerate pacing progressively; start with 2-second shots, end with 0.5second shots to build momentum. \u2022 Emotional beats : Linger on close-ups; 4-6 seconds minimum for moments of vulnerability, revelation, or decision. 1.3 The J-Cut and L-Cut \u2022 J-Cut: Audio from the next shot begins before the video cuts. Creates anticipation and smooths transitions. Use for scene introductions. \u2022 L-Cut: Audio from the current shot continues over the next shot's video. Maintains continuity and bridges spatial transitions. Use for dialogue overlap and scene exits. \u2022 Prometheus default: Apply J-cuts to",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk2",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 2,
    "content": "nt shot continues over the next shot's video. Maintains continuity and bridges spatial transitions. Use for dialogue overlap and scene exits. \u2022 Prometheus default: Apply J-cuts to scene openings, L-cuts to scene closings and dialogue exchanges. 2. TECHNICAL STANDARDS 2.1 Resolution & Aspect Ratio Guidelines Platform Resolution Aspect Ratio Frame Rate Codec Bitrate YouTube (4K) 3840x2160 16:9 24/30/60fps H.264/A V1 35-68 Mbps YouTube (1080p) 1920x1080 16:9 24/30/60fps H.264 8-12 Mbps Instagram Feed 1080x1080 1:1 30fps H.264 4-6 Mbps Instagram Reels 1080x1920 9:16 30/60fps H.264 6-8 Mbps TikTok 1080x1920 9:16 30/60fps H.264 6-8 Mbps Generated by Kimi.ai Table 1 - continued Platform Resolution Aspect Ratio Frame Rate Codec Bitrate LinkedIn 1920x1080 16:9 30fps H.264 5-8 Mbps Broadcast (US) 1920x1080 16:9 29.97fps ProRes 422 145 Mbps Broadcast (EU) 1920x1080 16:9 25fps ProRes 422 145 Mbps Cinema Delivery 4096x2160 1.9:1 24fps ProRes 4444 XQ 500+ Mbps Archive Master 3840x2160 16:9 Source fps ProRes 422 HQ 220 Mbps 2.2 F rame Rate Handling \u2022 Never mix frame rates on the same timeline without explicit conversion . Prometheus auto-converts using optical flow interpolation for 24->30fps and conform (drop/ repeat) for 30->24fps. \u2022 Slow motion : Shoot at 60fps+ for 24fps delivery; 120fps for 20% speed. Prometheus auto-detects high-frame-rate footage and suggests slow-motion interpretation. \u2022 Timecode: Use non-drop-frame for 24/25/30fps;",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk3",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 3,
    "content": "for 24fps delivery; 120fps for 20% speed. Prometheus auto-detects high-frame-rate footage and suggests slow-motion interpretation. \u2022 Timecode: Use non-drop-frame for 24/25/30fps; drop-frame only for 29.97fps broadcast. 2.3 Color Management \u2022 Color Space : Work in Rec. 709 for web delivery, Rec. 2020 for HDR, DCI-P3 for cinema. Never deliver in log or raw without proper grading. \u2022 Gamma: 2.4 for broadcast, 2.2 for web/sRGB. Prometheus auto-tags output metadata. \u2022 Skin T one Protection : Skin tones should fall between 50-75% IRE in waveform. Prometheus color matching prioritizes skin tone preservation over background accuracy. \u2022 LUT Application : Apply technical LUTs (log->Rec.709) before creative LUTs. Never stack more than 2 creative LUTs to avoid banding. 2.4 Audio Standards \u2022 Dialogue Levels : -23 LUFS (integrated) for broadcast, -16 LUFS for web/podcast, -14 LUFS for music-heavy content. \u2022 Peak Levels : Never exceed -1 dBTP (true peak). Prometheus applies true peak limiting at -1.5 dBTP for safety margin. \u2022 Dynamic Range : Dialogue should have 6-12 dB dynamic range. Music beds should sit 12-18 dB below dialogue. \u2022 Sample Rate : Record and deliver at 48 kHz for video. 44.1 kHz only for music-only deliverables. \u2022 Channel Mapping : Stereo = Ch1 Left, Ch2 Right. 5.1 = L, R, C, LFE, Ls, Rs. Never deliver mono dialogue unless specifically requested. 3. SHOT COMPOSITION & SELECTION 3.1 Shot Type Hierarchy for Editing \u2022",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk4",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 4,
    "content": "= Ch1 Left, Ch2 Right. 5.1 = L, R, C, LFE, Ls, Rs. Never deliver mono dialogue unless specifically requested. 3. SHOT COMPOSITION & SELECTION 3.1 Shot Type Hierarchy for Editing \u2022 Establishing Shot (ES) : Wide shot establishing location/context. Use once per scene or location change. Duration: 3-5 seconds. \u2022 Master Shot (MS) : Wide shot covering full action of a scene. Use as safety/base layer. Duration: full scene length. Generated by Kimi.ai \u2022 Medium Shot (Med) : Waist-up framing. Primary dialogue coverage. Most versatile shot type. \u2022 Close-Up (CU) : Head and shoulders. Emotional emphasis, reaction shots. Use sparingly for impact. \u2022 Extreme Close-Up (ECU) : Eyes, hands, objects. Detail emphasis, tension building. Duration: 1-3 seconds. \u2022 Insert (INS) : Object detail, text, action detail. Bridges gaps in master shot coverage. \u2022 Cutaway (CA) : Non-essential contextual shot. B-roll, environment, atmosphere. Use to cover jump cuts or compress time. 3.2 The 3-Shot Rule for Dialogue Never stay on the same shot type for more than 3 consecutive shots in a dialogue scene. Vary between: \u2022 Two-shot -> Medium -> Close-up -> Reaction -> Medium -> Two-shot This prevents visual monotony and maintains spatial awareness. 3.3 B-Roll Selection Criteria Prometheus scores B-roll candidates on: 1. Relevance: Visual content matches spoken keywords or narrative context (weight: 40%) 2. Visual Quality : Sharp focus, proper exposure, stable framing",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk5",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 5,
    "content": "ores B-roll candidates on: 1. Relevance: Visual content matches spoken keywords or narrative context (weight: 40%) 2. Visual Quality : Sharp focus, proper exposure, stable framing (weight: 25%) 3. Diversity: Shot scale/type differs from current A-roll (weight: 20%) 4. Motion: Contains subtle movement (water, tra\ufb00ic, leaves) to avoid static-image feel (weight: 15%) 4. TRANSITION BEST PRACTICES 4.1 When to Use Each T ransition Type \u2022 Hard Cut (90% of edits) : Default transition. Use for all dialogue, action, and narrative cuts. \u2022 Dissolve/Crossfade: Time passage, memory/flashback, emotional shift. Duration: 12-24 frames (0.5-1 second at 24fps). \u2022 F ade to Black: Scene end, emotional beat, act break. Duration: 24-48 frames. \u2022 F ade from Black: Scene opening, time jump, new location. Duration: 24-48 frames. \u2022 Wipe/Swipe: Stylistic only. Use for comedy, montage, or genre-specific sequences (sci-fi UI, news packages). \u2022 Morph/ Digital: Only when motivated by narrative (transformations, time travel, dream sequences). 4.2 T ransition Timing \u2022 Audio lead: Audio transitions should begin 2-6 frames before video transition (pre-lap) for smoothness. \u2022 Match cut: Align visual elements across cuts (shape, color, motion vector). Requires precise frame alignment. \u2022 Smash cut : Abrupt cut from quiet to loud or vice versa. Use for comedic or horror impact. Ensure 6+ dB level difference. Generated by Kimi.ai 5. COMMON TECHNICAL MISTAKES TO A",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk6",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 6,
    "content": "\u2022 Smash cut : Abrupt cut from quiet to loud or vice versa. Use for comedic or horror impact. Ensure 6+ dB level difference. Generated by Kimi.ai 5. COMMON TECHNICAL MISTAKES TO A VOID 1. Flash F rames: Single black or incorrectly exposed frames between cuts. Always check 1 frame before and after each cut point. 2. Audio Pops : Cuts at zero-crossings cause clicks. Apply 2-4 frame crossfades on all audio cuts unless hard sync is required. 3. Mismatched Eyelines : If character A looks screen-left in shot 1, character B must look screenright in shot 2. Reverse if crossing the line. 4. Jump Cuts : A void cutting between two shots of the same subject with similar framing. Use cutaway, B-roll, or dissolve. 5. Over-normalization: Bringing all audio to the same level destroys dynamic range. Preserve 6-12 dB range in dialogue. 6. Over-sharpening: Excessive sharpening creates halos and noise. Apply sharpening only in final delivery pass, never in proxies. 7. W rong Color Space Export : Exporting Rec. 709 content as sRGB or vice versa causes gamma shift. Always tag output color space correctly. 6. WORKFLOW OPTIMIZATION 6.1 Proxy W orkflow \u2022 Proxy ratio : 1/4 resolution (1080p->540p, 4K->1080p) at ProRes Proxy or H.264 low bitrate for smooth editing. \u2022 Relink strategy : Maintain original folder structure. Prometheus auto-generates proxies with preserved metadata for seamless relink. \u2022 Smart rendering : Only re-render changed segments.",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc2-chunk7",
    "source": "02_video_editing_best_practices.pdf",
    "title": "02 Video Editing Best Practices",
    "chunkIndex": 7,
    "content": "strategy : Maintain original folder structure. Prometheus auto-generates proxies with preserved metadata for seamless relink. \u2022 Smart rendering : Only re-render changed segments. Use preview renders for effects-heavy sections before final export. 6.2 V ersion Control \u2022 Naming convention : PROJECTNAME_DATE_VERSION_EDITORINITIALS (e.g., PROMETHEUS_DEMO_20260612_v03_JD) \u2022 Auto-save interval: 5 minutes maximum. Prometheus implements crash recovery with incremental backup. \u2022 Revision tracking : Lock approved sequences. Create new timeline versions for major revisions, not overwrite. 6.3 Render Queue Management \u2022 Priority order : Client review > internal review > social clips > archive master \u2022 Parallel rendering : Render multiple format variants simultaneously if hardware permits. Queue low-priority renders overnight. \u2022 Checksum verification: Always verify MD5/SHA-256 checksums after network transfers or cloud uploads. END OF VIDEO EDITING BEST PRACTICES DOCUMENT Generated by Kimi.ai",
    "tags": [
      "video",
      "editing",
      "best",
      "practices"
    ]
  },
  {
    "id": "doc3-chunk1",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 1,
    "content": "USER SCENARIOS, TROUBLESHOOTING & DECISION TREES - PROMETHEUS KNOWLEDGE BASE 1. COMMON USER SCENARIOS & PROMETHEUS RESPONSES SCENARIO 1: \"My footage is out of sync\" User Intent : Fix audio-video synchronization issue Prometheus Diagnostic Flow : 1. Check if sync drift is progressive (indicates sample rate mismatch) or sudden (indicates dropped frames) 2. If progressive: Detect source sample rates (44.1kHz vs 48kHz). Resample audio to match video sample rate. 3. If sudden: Check for variable frame rate (VFR) source footage. Convert to constant frame rate (CFR) using frame duplication or interpolation. 4. If multi-cam: Re-run sync using waveform analysis with 0.1-second tolerance window. 5. Apply slip/slide adjustment to affected clips. Generate sync map visualization for user review. T ool Calls: \u2022 analyze_sync_drift() -> detect_sample_rate() -> resample_audio() OR convert_vfr_to_cfr() -> apply_sync_correction() -> generate_sync_report() User Communication : \"I detected a 44.1kHz/48kHz sample rate mismatch causing progressive drift. I've resampled the audio and realigned all clips. The sync is now frame-accurate. Would you like me to flag any other clips with similar issues?\" SCENARIO 2: \"Make this video vertical for Instagram\" User Intent : Repurpose horizontal content for 9:16 social platform Prometheus Action Flow : 1. Analyze source aspect ratio (16:9, 21:9, etc.) and target (9:16) 2. Detect primary subjects using",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk2",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 2,
    "content": "Repurpose horizontal content for 9:16 social platform Prometheus Action Flow : 1. Analyze source aspect ratio (16:9, 21:9, etc.) and target (9:16) 2. Detect primary subjects using face/body detection and motion tracking 3. Calculate safe crop region that keeps subjects centered with 20% headroom 4. Apply smart reframing with keyframe animation for moving subjects 5. Generate 9:16 preview with auto-pan simulation 6. Export H.264 at 1080x1920, 30fps, with burned-in captions (social default) T ool Calls: \u2022 analyze_aspect_ratio() -> detect_primary_subjects() -> calculate_safe_crop() -> apply_smart_reframe() -> generate_preview() -> export_platform_format(platform=\"instagram_reels\") User Communication : \"I've reframed your video to 9:16 using smart tracking to keep your subjects centered. The auto-pan will follow movement smoothly. I've also burned in captions since 85% of social videos are watched without sound. Ready to export?\" Generated by Kimi.ai SCENARIO 3: \"The colors look different between my two cameras\" User Intent : Match color between mixed camera footage Prometheus Action Flow : 1. Analyze color histograms, white balance, and color temperature per camera source 2. Identify reference camera (typically the one with most footage or better dynamic range) 3. Extract color statistics from reference (midtones, highlights, shadow RGB balance) 4. Apply primary correction to secondary camera: lift/gamma/gain matching 5. Apply",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk3",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 3,
    "content": "mic range) 3. Extract color statistics from reference (midtones, highlights, shadow RGB balance) 4. Apply primary correction to secondary camera: lift/gamma/gain matching 5. Apply secondary correction: selective hue adjustments for skin tone protection 6. Generate side-by-side comparison with split-screen wipe 7. Create adjustment LUT for batch application to all secondary camera clips T ool Calls: \u2022 analyze_color_histogram() -> identify_reference_camera() -> extract_color_stats() -> apply_primary_correction() -> apply_skin_tone_protection() -> generate_comparison_view() -> export_matching_lut() User Communication : \"Camera A is cooler (5600K) and Camera B is warmer (6200K). I've matched Camera B to Camera A's color science while preserving natural skin tones. The difference is now imperceptible in the side-by-side comparison. Should I apply this to all clips from Camera B?\" SCENARIO 4: \"I need subtitles for this video\" User Intent : Generate and add captions/subtitles Prometheus Action Flow : 1. Extract audio track and run speech-to-text with speaker diarization 2. Apply punctuation restoration and capitalization rules 3. Detect language and offer translation if different from project default 4. Format captions: 32-character max per line, 2-line max, 1-second minimum duration, 0.3-second gap between captions 5. Style options: Open captions (burned-in) or closed captions (SRT/VTT) 6. For burned-in: Position at lower-third",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk4",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 4,
    "content": "max, 1-second minimum duration, 0.3-second gap between captions 5. Style options: Open captions (burned-in) or closed captions (SRT/VTT) 6. For burned-in: Position at lower-third with 10% safe margin, sans-serif font (Roboto or Arial), 4% of frame height, white text with 60% black background bar or drop shadow 7. For closed captions: Export SRT with proper timecode and sequential numbering T ool Calls: \u2022 extract_audio() -> speech_to_text() -> speaker_diarization() -> restore_punctuation() -> format_captions(style=\"burned_in\") -> export_captions(format=\"srt\") User Communication : \"I've generated captions with speaker labels and proper punctuation. The captions follow readability standards - max 2 lines, 1-second minimum display. I've positioned them in the lower-third safe area. Would you like them burned in or as a separate SRT file?\" Generated by Kimi.ai SCENARIO 5: \"This audio is too quiet/noisy\" User Intent : Fix audio quality issues Prometheus Action Flow : 1. Analyze audio: measure RMS, peak levels, noise floor, frequency spectrum 2. If quiet: Apply gain staging (normalize to -23 LUFS integrated), then compression (2:1 ratio, -18dB threshold, 10ms attack, 100ms release) 3. If noisy: Apply adaptive noise reduction (spectral subtraction with 6dB noise floor reduction). Preserve dialogue clarity above 2kHz. 4. If echoey: Apply de-reverberation (early reflection suppression, not full reverb removal to avoid artifacts) 5. If",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk5",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 5,
    "content": "noise floor reduction). Preserve dialogue clarity above 2kHz. 4. If echoey: Apply de-reverberation (early reflection suppression, not full reverb removal to avoid artifacts) 5. If inconsistent levels: Apply auto-leveling with 3-second window and 2dB max gain change per second 6. Generate before/after waveform comparison T ool Calls: \u2022 analyze_audio_profile() -> if_noise_floor_high: apply_noise_reduction() -> if_levels_low: apply_normalization(target=\"-23_LUFS\") -> if_dynamic_range_excessive: apply_compression(ratio=2, threshold=-18) -> generate_waveform_comparison() User Communication : \"The audio has a -42dB noise floor and peaks at -12dB. I've applied noise reduction (6dB suppression), normalized to -23 LUFS, and added light compression for consistency. The dialogue is now clear and broadcast-compliant. Here's the before/after comparison. \" SCENARIO 6: \"Export this in multiple formats\" User Intent : Generate multiple deliverables from one timeline Prometheus Action Flow : 1. Parse user intent: Which platforms? (YouTube, Instagram, TikTok, client review, broadcast?) 2. Create render queue with platform-optimized presets: \u2022 Master: ProRes 422 HQ, source resolution, source frame rate \u2022 Web Review: H.264, 1080p, 8Mbps, stereo audio \u2022 Social Vertical: H.264, 1080x1920, 6Mbps, burned captions \u2022 Social Square: H.264, 1080x1080, 6Mbps \u2022 Audio Only: W A V 48kHz/24-bit or MP3 320kbps 3. Apply platform-specific requirements (duration",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk6",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 6,
    "content": "H.264, 1080x1920, 6Mbps, burned captions \u2022 Social Square: H.264, 1080x1080, 6Mbps \u2022 Audio Only: W A V 48kHz/24-bit or MP3 320kbps 3. Apply platform-specific requirements (duration limits, safe margins, codec compliance) 4. Parallel render if hardware allows; sequential if resource-constrained 5. Generate checksums and upload to designated cloud destination 6. Create delivery notes document with technical specs per file T ool Calls: Generated by Kimi.ai \u2022 parse_delivery_requirements() -> create_render_queue() -> apply_platform_preset(platform_list) -> execute_parallel_render() -> verify_checksums() -> upload_to_cloud() -> generate_delivery_notes() User Communication : \"I've queued 5 deliverables: 4K ProRes master, 1080p review copy, 9:16 Reels, 1:1 feed post, and W A V audio. All are optimized for their platforms with correct specs. Rendering now - estimated 12 minutes. I'll notify you when complete and upload to your Frame.io folder. \" SCENARIO 7: \"Find the best moments from this long video\" User Intent : Extract highlights or create a summary reel Prometheus Action Flow : 1. Scene detection: Identify shot boundaries and scene changes 2. Audio analysis: Detect applause, laughter, music swells, dramatic pauses 3. Visual analysis: Detect camera movement (pans, zooms), face expressions (smiles, surprise), texton-screen 4. Content scoring: Rank segments by energy level, emotional valence, visual variety, audio clarity 5. User",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk7",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 7,
    "content": "ement (pans, zooms), face expressions (smiles, surprise), texton-screen 4. Content scoring: Rank segments by energy level, emotional valence, visual variety, audio clarity 5. User preference learning: Weight segments similar to previously accepted highlights 6. Generate 3 highlight options: 30-second teaser, 2-minute summary, 5-minute best-of 7. Present options with thumbnail previews and confidence scores T ool Calls: \u2022 run_scene_detection() -> analyze_audio_events() -> analyze_visual_events() -> score_content_segments() -> apply_user_preference_weights() -> generate_highlight_options(durations=[30, 120, 300]) -> create_thumbnail_previews() User Communication : \"I found 12 high-energy moments in your 45-minute video. I've assembled three options: a 30-second teaser (best for social), a 2-minute summary (best for email), and a 5-minute extended cut (best for website). Each is ranked by engagement potential. Preview them here and let me know which to refine. \" 2. TROUBLESHOOTING DECISION TREE ISSUE: Render F ailed / Export Error START \u2502 \u251c\u2500 Error Type: \"Codec not found\" or \"Unsupported format\" \u2502 \u2514\u2500 ACTION: Check source codec compatibility. Transcode source to ProRes or DNxHD before editing. \u2502 \u251c\u2500 Error Type: \"Disk full\" or \"Insufficient space\" \u2502 \u2514\u2500 ACTION: Calculate required space (source \u00d7 3 for proxies + render). Purge old renders or select lower-bitrate preset.\u21aa \u2502 \u251c\u2500 Error Type: \"GPU out of memory\" Generated by Kimi.ai \u2502 \u2514\u2500",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk8",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 8,
    "content": "TION: Calculate required space (source \u00d7 3 for proxies + render). Purge old renders or select lower-bitrate preset.\u21aa \u2502 \u251c\u2500 Error Type: \"GPU out of memory\" Generated by Kimi.ai \u2502 \u2514\u2500 ACTION: Reduce timeline resolution, disable GPU-accelerated effects, or switch to software rendering.\u21aa \u2502 \u251c\u2500 Error Type: \"Audio sample rate mismatch\" \u2502 \u2514\u2500 ACTION: Identify mismatched clips. Resample all to 48kHz before export. \u2502 \u251c\u2500 Error Type: \"Frame rate mismatch on timeline\" \u2502 \u2514\u2500 ACTION: Create separate timelines per frame rate, or conform all footage to project frame rate. \u2502 \u2514\u2500 Error Type: \"Media offline\" or \"File not found\" \u2514\u2500 ACTION: Re-link media using original folder structure. If moved, use search-and-relink with file naming patterns.\u21aa ISSUE: Playback Stuttering / Dropped F rames START \u2502 \u251c\u2500 Check proxy status: Are proxies generated? \u2502 \u251c\u2500 YES: Switch to proxy playback (1/4 res). Check GPU driver update. \u2502 \u2514\u2500 NO: Generate proxies for all footage. Enable background proxy generation. \u2502 \u251c\u2500 Check storage speed: Is source media on SSD or network drive? \u2502 \u251c\u2500 SSD: Check disk health (SMART status). Fragmentation unlikely on SSD. \u2502 \u2514\u2500 Network / HDD: Move active project to local SSD. Network drives cause I/O bottlenecks. \u2502 \u251c\u2500 Check effects load: Are there unrendered effects? \u2502 \u251c\u2500 YES: Pre-render effects-heavy sections. Disable real-time preview for complex color grades. \u2502 \u2514\u2500 NO: Reduce playback resolution to 1/2 or 1/4. Disable scopes and waveform",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk9",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 9,
    "content": "ts? \u2502 \u251c\u2500 YES: Pre-render effects-heavy sections. Disable real-time preview for complex color grades. \u2502 \u2514\u2500 NO: Reduce playback resolution to 1/2 or 1/4. Disable scopes and waveform displays. \u2502 \u2514\u2500 Check system resources: CPU/GPU/RAM usage? \u251c\u2500 RAM >90%: Close other applications. Increase page file size. Reduce undo levels. \u2514\u2500 CPU/GPU throttling: Check thermal status. Clean dust filters. Reduce power-saving settings. ISSUE: Color Looks W rong After Export START \u2502 \u251c\u2500 Check export color space tag: Is it tagged correctly? \u2502 \u251c\u2500 Rec. 709 content tagged as sRGB -> Gamma shift (darker on web players) \u2502 \u251c\u2500 Rec. 709 content tagged as Rec. 601 -> Slight color shift (older standard) \u2502 \u2514\u2500 Untagged -> Player assumes sRGB, may cause gamma mismatch \u2502 \u251c\u2500 Check monitor calibration: Is editing monitor profiled? \u2502 \u251c\u2500 NO: Export will look different on every screen. Use reference monitor or calibration probe. \u2502 \u2514\u2500 YES: Check if export is being viewed in color-managed app (QuickTime vs VLC vs browser) \u2502 \u251c\u2500 Check LUT stacking: Multiple LUTs applied? \u2502 \u2514\u2500 YES: Remove technical LUT before applying creative LUT. Never apply LUT to already-graded footage. \u2502 \u2514\u2500 Check bit depth: 8-bit export from 10-bit source? Generated by Kimi.ai \u2514\u2500 YES: Banding in gradients. Export to 10-bit (ProRes 422 HQ) or dither to 8-bit with noise grain. 3. TOOL CALLING LOGIC MATRIX User Says Intent Detected Primary Tool Secondary Tools Confidence \"sync my clips\" Audio sync",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk10",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 10,
    "content": "-bit (ProRes 422 HQ) or dither to 8-bit with noise grain. 3. TOOL CALLING LOGIC MATRIX User Says Intent Detected Primary Tool Secondary Tools Confidence \"sync my clips\" Audio sync auto_sync_multicam() drift_correction() , generate_sync_map() 95% \"make this vertical\" Format conversion smart_reframe() export_platform_format(), burn_captions() 98% \"colors don 't match\" Color correction auto_color_match() skin_tone_protection() , generate_comparison() 92% \"add subtitles\" Caption generation auto_transcribe() speaker_diarization() , format_captions() 99% \"fix audio\" Audio repair analyze_audio_profile() noise_reduction(), normalization(), compression() 85% (ambiguous) \"export for YouTube\" Platform export apply_platform_preset() render_queue(), upload_to_cloud() 96% \"find best moments\" Highlight extraction score_content_segments() scene_detection(), generate_highlight_reel() 94% \"too long, cut it down\" Time compression auto_assembly_cut() content_scoring() , pace_analysis() 88% \"add music\" Music licensing search_music_library() audio_ducking(), beat_matching() 90% \"stabilize this\" Camera stabilization auto_stabilize() crop_compensation(), rolling_shutter_repair() 97% \"remove this object\" VFX cleanup content_aware_fill() motion_tracking() , plate_extraction() 89% \"make it cinematic\" Creative grading apply_creative_lut() letterbox_overlay() , film_grain(), chromatic_aberration() 78% (subjective) 4. ESCALATION PATHS When Prometheus",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc3-chunk11",
    "source": "03_user_scenarios_troubleshooting.pdf",
    "title": "03 User Scenarios Troubleshooting",
    "chunkIndex": 11,
    "content": "ion() 89% \"make it cinematic\" Creative grading apply_creative_lut() letterbox_overlay() , film_grain(), chromatic_aberration() 78% (subjective) 4. ESCALATION PATHS When Prometheus confidence is below 80% or user rejects 3+ consecutive suggestions: 1. Clarify Intent : Ask specific questions rather than making assumptions. \"Do you want to remove the background noise, or boost the dialogue volume, or both?\" 2. Present Options : Show 2-3 approaches with trade-offs. \"Option A preserves natural dynamics but requires manual tweaking. Option B applies auto-leveling but may sound compressed. \" 3. Learn Preference: Log user choice and apply to future projects. \"I'll remember you prefer manual control over auto-correction for dialogue. \" Generated by Kimi.ai 4. Human Handoff : For creative decisions (pacing, emotional beats, music selection), present options but defer final decision to user. \"Here are 3 music options ranked by mood match. Which fits your vision?\" END OF USER SCENARIOS & TROUBLESHOOTING DOCUMENT Generated by Kimi.ai",
    "tags": [
      "user",
      "scenarios",
      "troubleshooting"
    ]
  },
  {
    "id": "doc4-chunk1",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 1,
    "content": "TOOL CALLING GUIDE & API REFERENCE - PROMETHEUS KNOWLEDGE BASE 1. TOOL INVENTORY 1.1 MEDIA INGESTION & MANAGEMENT ingest_media(source_path, project_id, auto_proxy=True) Purpose: Import raw footage, audio, and graphics into the project Parameters: \u2022 source_path (str): File path, URL, or cloud storage URI \u2022 project_id (str): Target project identifier \u2022 auto_proxy (bool): Generate editing proxies automatically Returns: Media object with metadata (codec, resolution, duration, timecode, checksum) When to Call : At project start, when new footage arrives, or when importing from cloud T rigger Phrases: \"import footage\", \"add media\", \"bring in files\", \"download from cloud\" organize_media(project_id, folder_structure=\"scene_based\") Purpose: Sort media into bins/folders by scene, shot type, date, or camera Parameters: \u2022 project_id (str): Target project \u2022 folder_structure (str): \"scene_based\", \"date_based\", \"camera_based\", \"shot_type_based\" Returns: Folder hierarchy with media assignments When to Call : After ingestion, when user says \"organize my footage\", \"sort clips\", \"bin my media\" T rigger Phrases: \"organize\", \"sort\", \"bin\", \"folder structure\", \"arrange clips\" generate_proxies(media_list, resolution_ratio=0.25, codec=\"ProRes Proxy\") Purpose: Create lightweight editing proxies for smooth playback Parameters: \u2022 media_list (list): Media objects to proxy \u2022 resolution_ratio (float): 0.25=quarter-res, 0.5=half-res \u2022 codec (str): \"ProRes",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk2",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 2,
    "content": "eight editing proxies for smooth playback Parameters: \u2022 media_list (list): Media objects to proxy \u2022 resolution_ratio (float): 0.25=quarter-res, 0.5=half-res \u2022 codec (str): \"ProRes Proxy\", \"H.264 Low\", \"DNxHR LB\" Returns: Proxy file paths with relink metadata When to Call : After ingestion on 4K+ footage, when playback is stuttering, or when working on remote/cloud media T rigger Phrases: \"create proxies\", \"make lightweight versions\", \"playback is slow\", \"stuttering\" 1.2 SYNC & ASSEMBL Y auto_sync_multicam(media_list, sync_method=\"audio_waveform\", tolerance=0.1) Purpose: Synchronize multiple camera angles and audio sources Parameters: \u2022 media_list (list): Clips to sync \u2022 sync_method (str): \"audio_waveform\", \"timecode\", \"visual_marker\", \"manual_in\" \u2022 tolerance (float): Maximum drift in seconds before flagging Returns: Sync map with offset values and confidence scores per clip When to Call : On multi-cam projects, when user reports sync issues, or after ingesting new angles T rigger Phrases: \"sync my clips\", \"multi-cam sync\", \"audio is out of sync\", \"line up footage\", \"match audio\" Generated by Kimi.ai drift_correction(sync_map, reference_clip) Purpose: Fix progressive sync drift caused by sample rate mismatches Parameters: \u2022 sync_map (object): Output from auto_sync_multicam \u2022 reference_clip (str): The clip to use as timing standard Returns: Corrected sync map with perframe offset adjustments When to Call : When auto_sync shows",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk3",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 3,
    "content": "from auto_sync_multicam \u2022 reference_clip (str): The clip to use as timing standard Returns: Corrected sync map with perframe offset adjustments When to Call : When auto_sync shows progressive drift >2 frames over 10 minutes T rigger Phrases: \"drift\", \"progressive sync issue\", \"getting worse over time\", \"long clip sync\" auto_assembly_cut(script_text, media_pool, style=\"dialogue_driven\") Purpose: Generate rough cut by aligning script/transcript with footage Parameters: \u2022 script_text (str): Script or transcript content \u2022 media_pool (list): A vailable media objects \u2022 style (str): \"dialogue_driven\", \"visual_driven\", \"music_driven\", \"chronological\" Returns: Timeline object with edit decision list (EDL) When to Call : At project start for documentary/interview content, when user says \"start editing\", \"rough cut\" T rigger Phrases: \"assembly cut\", \"rough cut\", \"start editing\", \"first pass\", \"auto edit\", \"generate timeline\" insert_broll(edl, broll_pool, relevance_threshold=0.7, max_coverage=0.4) Purpose: Automatically insert B-roll over dialogue or transitional sections Parameters: \u2022 edl (object): Edit decision list from assembly cut \u2022 broll_pool (list): A vailable B-roll media \u2022 relevance_threshold (float): 0.0-1.0 minimum keyword/context match score \u2022 max_coverage (float): Maximum fraction of timeline to cover with B-roll (prevents overuse) Returns: Updated EDL with B-roll insertion points and duration When to Call : After assembly",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk4",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 4,
    "content": "coverage (float): Maximum fraction of timeline to cover with B-roll (prevents overuse) Returns: Updated EDL with B-roll insertion points and duration When to Call : After assembly cut, when user wants \"more visuals\", \"cover the talking heads\", \"add B-roll\" T rigger Phrases: \"add B-roll\", \"cover interview\", \"more visuals\", \"insert cutaways\", \"break up talking heads\" 1.3 COLOR & IMAGE auto_color_match(target_clip, reference_clip, protect_skin=True) Purpose: Match color between two clips or camera sources Parameters: \u2022 target_clip (str): Clip to correct \u2022 reference_clip (str): Reference clip to match \u2022 protect_skin (bool): Preserve natural skin tones during matching Returns: Color correction parameters (lift, gamma, gain, saturation, hue shifts) When to Call : When user reports color mismatch between cameras, after adding new footage to graded sequence T rigger Phrases: \"match color\", \"colors don't match\", \"make them look the same\", \"white balance fix\", \"color correction\" apply_creative_lut(clip_list, lut_name, intensity=1.0) Purpose: Apply look-up table for stylistic color grading Parameters: \u2022 clip_list (list): Clips to grade Generated by Kimi.ai \u2022 lut_name (str): LUT identifier (e.g., \"TealOrange_Cinematic\", \"Vintage_70s\", \"Bleach_Bypass\") \u2022 intensity (float): 0.0-1.0 blend factor Returns: Graded clip previews When to Call : During creative grading phase, when user requests a specific look T rigger Phrases: \"make it",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk5",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 5,
    "content": "\u2022 intensity (float): 0.0-1.0 blend factor Returns: Graded clip previews When to Call : During creative grading phase, when user requests a specific look T rigger Phrases: \"make it cinematic\", \"apply LUT\", \"color grade\", \"film look\", \"vintage look\", \"teal and orange\" smart_reframe(clip_list, target_aspect_ratio, subject_tracking=True) Purpose: Convert horizontal footage to vertical or square while keeping subjects centered Parameters: \u2022 clip_list (list): Clips to reframe \u2022 target_aspect_ratio (str): \"9:16\", \"1:1\", \"4:5\", \"2.39:1\" \u2022 subject_tracking (bool): Enable AI subject tracking with keyframe animation Returns: Reframed clips with pan/ scan keyframe data When to Call : For social media repurposing, when user says \"make vertical\", \"Instagram format\", \"TikTok\" T rigger Phrases: \"vertical video\", \"make it square\", \"9:16\", \"social media format\", \"reframe\", \"crop for phone\" auto_stabilize(clip_list, smoothness=0.5, crop_margin=0.1) Purpose: Remove camera shake and smooth unwanted motion Parameters: \u2022 clip_list (list): Clips to stabilize \u2022 smoothness (float): 0.0=locked tripod, 1.0=handheld feel preserved \u2022 crop_margin (float): Percentage of frame to allow for compensation (0.05-0.2) Returns: Stabilized clips with motion vector data When to Call : On handheld footage, drone footage with wind shake, or telephoto wobble T rigger Phrases: \"stabilize\", \"remove shake\", \"smooth footage\", \"too shaky\", \"handheld fix\" 1.4 AUDIO",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk6",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 6,
    "content": "ll : On handheld footage, drone footage with wind shake, or telephoto wobble T rigger Phrases: \"stabilize\", \"remove shake\", \"smooth footage\", \"too shaky\", \"handheld fix\" 1.4 AUDIO analyze_audio_profile(clip_list) Purpose: Measure audio characteristics for diagnostic and correction planning Parameters: \u2022 clip_list (list): Clips to analyze Returns: Profile data (RMS, peak, LUFS, noise floor, frequency spectrum, dynamic range) When to Call : Before any audio correction, when user reports audio issues, as first diagnostic step T rigger Phrases: \"analyze audio\", \"check audio levels\", \"audio profile\", \"what's wrong with sound\", \"audio diagnostic\" apply_normalization(clip_list, target_lufs=-23.0, true_peak_limit=-1.5) Purpose: Bring audio to standard loudness with peak protection Parameters: \u2022 clip_list (list): Clips to process \u2022 target_lufs (float): Target integrated loudness (-23 for broadcast, -16 for web, -14 for music) \u2022 true_peak_limit (float): Maximum true peak in dBTP Returns: Normalized clips with loudness report When to Call : On dialogue tracks, before delivery, when audio is too quiet or inconsistent T rigger Phrases: \"normalize audio\", \"make it louder\", \"fix levels\", \"broadcast loudness\", \"LUFS\" Generated by Kimi.ai apply_noise_reduction(clip_list, reduction_db=6.0, preserve_freq=2000) Purpose: Remove background noise while preserving dialogue clarity Parameters: \u2022 clip_list (list): Clips to process \u2022 reduction_db",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk7",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 7,
    "content": "clip_list, reduction_db=6.0, preserve_freq=2000) Purpose: Remove background noise while preserving dialogue clarity Parameters: \u2022 clip_list (list): Clips to process \u2022 reduction_db (float): Amount of noise reduction (3-12dB typical) \u2022 preserve_freq (int): Frequency above which to preserve content (dialogue clarity) Returns: Cleaned clips with noise profile When to Call : On location audio with HV AC, wind, tra\ufb00ic, or electrical hum T rigger Phrases: \"remove noise\", \"clean audio\", \"hiss removal\", \"background noise\", \"audio cleanup\" apply_compression(clip_list, ratio=2.0, threshold=-18.0, attack_ms=10, release_ms=100) Purpose: Reduce dynamic range for consistent playback Parameters: \u2022 clip_list (list): Clips to process \u2022 ratio (float): Compression ratio (1.5:1 subtle, 4:1 aggressive) \u2022 threshold (float): dB level where compression begins \u2022 attack_ms (int): How quickly compression engages \u2022 release_ms (int): How quickly compression disengages Returns: Compressed clips with gain reduction graph When to Call : On dialogue with inconsistent levels, when whisper-to-shout ratio is too wide T rigger Phrases: \"compress audio\", \"even out levels\", \"dialogue consistency\", \"dynamic range\", \"audio leveling\" audio_ducking(music_track, dialogue_track, attenuation_db=-12, lookahead_ms=50) Purpose: Automatically lower music when dialogue is present Parameters: \u2022 music_track (str): Music clip to duck \u2022 dialogue_track (str): Dialogue reference",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk8",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 8,
    "content": "db=-12, lookahead_ms=50) Purpose: Automatically lower music when dialogue is present Parameters: \u2022 music_track (str): Music clip to duck \u2022 dialogue_track (str): Dialogue reference track \u2022 attenuation_db (float): How much to lower music (-6 to -18dB typical) \u2022 lookahead_ms (int): Pre-emptive ducking before dialogue starts Returns: Ducking envelope with keyframe data When to Call : When mixing music under voiceover, documentary narration, or interview B-roll T rigger Phrases: \"duck music\", \"lower music under voice\", \"mix music and dialogue\", \"background music levels\" 1.5 TEXT & CAPTIONS auto_transcribe(audio_track, language=\"auto\", speaker_diarization=True) Purpose: Convert speech to text with punctuation and speaker labels Parameters: \u2022 audio_track (str): Audio file or timeline track to transcribe \u2022 language (str): Language code or \"auto\" for detection \u2022 speaker_diarization (bool): Identify different speakers Returns: Transcript with timecodes, speaker labels, and confidence scores When to Call : For caption generation, script alignment, content search, or logging T rigger Phrases: \"transcribe\", \"generate transcript\", \"speech to text\", \"get captions\", \"subtitles\" Generated by Kimi.ai format_captions(transcript, style=\"burned_in\", max_chars=32, max_lines=2, min_duration=1.0) Purpose: Convert transcript to readable caption format Parameters: \u2022 transcript (object): Output from auto_transcribe \u2022 style (str): \"burned_in\", \"srt\",",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk9",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 9,
    "content": "lines=2, min_duration=1.0) Purpose: Convert transcript to readable caption format Parameters: \u2022 transcript (object): Output from auto_transcribe \u2022 style (str): \"burned_in\", \"srt\", \"vtt\", \"ass\" \u2022 max_chars (int): Maximum characters per line \u2022 max_lines (int): Maximum lines per caption \u2022 min_duration (float): Minimum seconds per caption Returns: Formatted caption file or burn-in parameters When to Call : After transcription, before export, when user requests specific caption style T rigger Phrases: \"format captions\", \"burn in subtitles\", \"SRT export\", \"caption style\", \"subtitle format\" 1.6 EXPOR T & DELIVER Y apply_platform_preset(platform_name, clip_list) Purpose: Apply platform-specific encoding and formatting settings Parameters: \u2022 platform_name (str): \"youtube_4k\", \"youtube_1080\", \"instagram_reels\", \"tiktok\", \"linkedin\", \"broadcast_ntsc\", \"broadcast_pal\", \"prores_master\" \u2022 clip_list (list): Clips to process Returns: Render preset with all technical parameters populated When to Call : Before final export, when user specifies delivery platform T rigger Phrases: \"export for YouTube\", \"Instagram format\", \"TikTok video\", \"broadcast delivery\", \"ProRes master\" create_render_queue(preset_list, parallel=True) Purpose: Queue multiple format exports for batch processing Parameters: \u2022 preset_list (list): List of platform presets to render \u2022 parallel (bool): Render simultaneously if hardware supports Returns: Queue object with job IDs,",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk10",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 10,
    "content": "h processing Parameters: \u2022 preset_list (list): List of platform presets to render \u2022 parallel (bool): Render simultaneously if hardware supports Returns: Queue object with job IDs, estimated times, and dependencies When to Call : When multiple deliverables needed from same timeline T rigger Phrases: \"batch export\", \"render queue\", \"multiple formats\", \"export all\", \"deliverables\" verify_render(output_file, source_checksum) Purpose: Validate exported file integrity and spec compliance Parameters: \u2022 output_file (str): Path to rendered file \u2022 source_checksum (str): Expected checksum for verification Returns: Verification report (pass/fail, error details, frame count match, bitrate check) When to Call : After each render completes, before delivery to client T rigger Phrases: \"verify export\", \"check render\", \"validate file\", \"corruption check\", \"checksum\" upload_to_cloud(file_list, destination=\"frameio\", folder_path=\"/\") Purpose: Upload deliverables to cloud storage or review platform Parameters: \u2022 file_list (list): Files to upload \u2022 destination (str): \"frameio\", \"dropbox\", \"gdrive\", \"s3\", \"azure\", \"asana\", \"trello\" Generated by Kimi.ai \u2022 folder_path (str): Target folder in destination Returns: Upload confirmation with shareable links and access permissions When to Call : After render verification, when user says \"send to client\", \"upload\", \"share link\" T rigger Phrases: \"upload to Frame.io\", \"send to Dropbox\", \"cloud upload\",",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk11",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 11,
    "content": "ssions When to Call : After render verification, when user says \"send to client\", \"upload\", \"share link\" T rigger Phrases: \"upload to Frame.io\", \"send to Dropbox\", \"cloud upload\", \"share with client\", \"delivery link\" 1.7 QUALITY ASSURANCE run_technical_qc(timeline, check_flash_frames=True, check_audio_peaks=True, check_black_frames=True) Purpose: Detect technical errors in the timeline before export Parameters: \u2022 timeline (object): Timeline to analyze \u2022 check_flash_frames (bool): Detect single-frame anomalies \u2022 check_audio_peaks (bool): Detect clipping and level violations \u2022 check_black_frames (bool): Detect unintended black frames Returns: QC report with timestamps, severity levels, and suggested fixes When to Call : Before final export, after major edit changes, as part of delivery workflow T rigger Phrases: \"QC check\", \"technical review\", \"find errors\", \"flash frames\", \"black frames\", \"audio peaks\" generate_delivery_notes(render_jobs, project_metadata) Purpose: Create technical specification document for client handoff Parameters: \u2022 render_jobs (list): Completed render queue items \u2022 project_metadata (object): Project name, editor, date, client info Returns: Formatted delivery notes (PDF/markdown) with specs per file When to Call : After all renders complete, before final delivery T rigger Phrases: \"delivery notes\", \"tech specs\", \"spec sheet\", \"client handoff\", \"delivery document\" 2. TOOL SEQUENCING PATTERNS P A TTERN A:",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk12",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 12,
    "content": "ders complete, before final delivery T rigger Phrases: \"delivery notes\", \"tech specs\", \"spec sheet\", \"client handoff\", \"delivery document\" 2. TOOL SEQUENCING PATTERNS P A TTERN A: Standard Interview/Documentary W orkflow ingest_media() -> organize_media() -> auto_sync_multicam() -> auto_assembly_cut() -> insert_broll() -> auto_color_match() -> apply_normalization() -> auto_transcribe() -> format_captions() -> run_technical_qc() -> apply_platform_preset() -> create_render_queue() -> verify_render() -> upload_to_cloud() -> generate_delivery_notes() P A TTERN B: Social Media Repurpose W orkflow ingest_media() -> smart_reframe(target=\"9:16\") -> auto_transcribe() -> format_captions(style=\"burned_in\") -> apply_platform_preset(\"instagram_reels\") -> apply_platform_preset(\"tiktok\") -> create_render_queue() -> upload_to_cloud() P A TTERN C: Audio-First Podcast/VO W orkflow analyze_audio_profile() -> apply_noise_reduction() -> apply_compression() -> Generated by Kimi.ai apply_normalization(target_lufs=-16) -> audio_ducking() -> auto_transcribe() -> format_captions(style=\"srt\") -> export_audio_only() P A TTERN D: Multi-Cam Live Event W orkflow ingest_media() -> auto_sync_multicam(sync_method=\"timecode\") -> generate_proxies() -> auto_assembly_cut(style=\"chronological\") -> score_content_segments() -> generate_highlight_reel() -> apply_platform_preset() -> create_render_queue(parallel=True) 3. ERROR HANDLING & F ALLBACKS Tool Failure",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc4-chunk13",
    "source": "04_tool_calling_guide.pdf",
    "title": "04 Tool Calling Guide",
    "chunkIndex": 13,
    "content": "ronological\") -> score_content_segments() -> generate_highlight_reel() -> apply_platform_preset() -> create_render_queue(parallel=True) 3. ERROR HANDLING & F ALLBACKS Tool Failure Fallback Action User Message auto_sync_multicam() fails on audio Try sync_method=\"timecode\" then sync_method=\"visual_marker\" \"Audio sync failed -trying timecode alignment instead. \" auto_color_match() produces unnatural skin Enable protect_skin=True, reduce match intensity to 0.7 \"Color match was too aggressive -I've dialed it back to preserve natural skin tones. \" auto_transcribe() low confidence Flag segments for manual review, suggest language specification \"Transcription confidence is low on some segments. Could you confirm the primary language?\" smart_reframe() subject tracking lost Increase crop_margin to 0.15, add manual keyframe suggestion \"Subject moved too fast for auto-tracking. I 've widened the crop -please review 3 flagged segments. \" apply_platform_preset() unsupported codec Transcode to intermediate ProRes, then apply preset \"Source codec isn 't compatible with direct export. Transcoding to ProRes first -this adds 2 minutes. \" upload_to_cloud() network timeout Queue for retry with exponential backoff, offer local save \"Upload timed out. I 'll retry in 30 seconds, or I can save locally if you prefer. \" END OF TOOL CALLING GUIDE & API REFERENCE DOCUMENT Generated by Kimi.ai",
    "tags": [
      "tool",
      "calling",
      "guide"
    ]
  },
  {
    "id": "doc5-chunk1",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 1,
    "content": "CREATIVE WORKFLOWS & GENRE-SPECIFIC EDITING PROMETHEUS KNOWLEDGE BASE 1. GENRE-SPECIFIC EDITING PRINCIPLES 1.1 Narrative / Drama Pacing Philosophy : Invisible editing serves the story. Cuts are motivated by emotion, not action. \u2022 Dialogue Scenes : Use the \"reaction shot rule\" - cut to the listener 1-2 seconds BEFORE the speaker finishes, capturing the emotional response. This creates subtext. \u2022 T ension Building: Extend shot duration as tension rises. A 10-second close-up on a character's eyes before a decision creates more tension than rapid cutting. \u2022 Flashbacks / Memory : Use dissolves (18-24 frames) with slight desaturation (-20%) and lifted blacks (milky shadows) to signal temporal shift. \u2022 Revelation Moments : Hold on the reacting character, not the revealed object. The audience cares about the impact, not the object itself. \u2022 Prometheus Default : For drama, disable auto-cut suggestions. Enable \"emotion detection\" to flag moments where extended holds are recommended. 1.2 Documentary / Interview Pacing Philosophy : Truthful pacing respects real time. Let subjects breathe. \u2022 The Pause Rule : Never cut during a subject's pause shorter than 1.5 seconds. Pauses convey thought, emotion, and authenticity. Cutting too early destroys credibility. \u2022 B-Roll Strategy : Use B-roll to cover cuts in interview, but never cover the most emotional or impactful statements. Let the audience see the subject's face during vulnerability. \u2022",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk2",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 2,
    "content": "-Roll Strategy : Use B-roll to cover cuts in interview, but never cover the most emotional or impactful statements. Let the audience see the subject's face during vulnerability. \u2022 Archival Integration: When mixing archival footage with modern interviews, apply subtle film grain, slight vignette, and 5% desaturation to archival to distinguish eras without jarring contrast. \u2022 The \"Noddies\" : Reaction shots of interviewer nodding should be used sparingly. Prometheus flags overuse and suggests cutaways to environment or detail instead. \u2022 Prometheus Default : Enable auto-transcription with speaker diarization. Use transcript gaps >2 seconds as B-roll insertion points. Suggest B-roll based on keyword matching. 1.3 Commercial / Advertising Pacing Philosophy : Every frame sells. Maximum information density, minimum duration. \u2022 The 3-Second Rule : Hook the viewer in the first 3 seconds. If the opening shot doesn't contain motion, product, or face, flag for replacement. \u2022 Product Hero Shots : Hold on product for minimum 1.5 seconds. Use macro/close-up to show texture. Add subtle rotation or light movement to prevent static feel. \u2022 Pacing Curve : Start fast (0.8-second shots), slow for product reveal (2-3 seconds), accelerate to call-to-action (0.5-second shots). Generated by Kimi.ai \u2022 Logo Lockup : End with 2-second minimum logo hold. Never cut during logo animation - let it resolve completely. \u2022 Music Sync : Cut on beat for",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk3",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 3,
    "content": "econd shots). Generated by Kimi.ai \u2022 Logo Lockup : End with 2-second minimum logo hold. Never cut during logo animation - let it resolve completely. \u2022 Music Sync : Cut on beat for high-energy spots. Use waveform analysis to identify downbeats and align cuts 2-3 frames before the beat for impact. \u2022 Prometheus Default : Enable \"beat matching\" for music-driven cuts. Set max shot duration to 2 seconds for 15-30 second spots. Auto-flag static shots >2 seconds. 1.4 Music Video Pacing Philosophy : Visual rhythm matches musical rhythm. The edit IS the performance. \u2022 Beat-Cut Alignment : Primary cuts align with snare/kick drum hits. Secondary cuts align with hi-hats or lyrical phrases for layered rhythm. \u2022 Performance vs. Narrative : 70% performance footage (artist lip-sync), 30% narrative/abstract. For rap/hip-hop, increase performance to 85%. \u2022 Speed Ramps : Use speed ramps (100%->25%->100%) on impactful beats or emotional lyrical moments. Duration: 12-18 frames for the ramp. \u2022 Multi-Layer Sync: When cutting between multiple performance takes, sync all takes to the same audio waveform reference. Even slight sync drift destroys the illusion. \u2022 Prometheus Default : Enable \"beat detection\" and \"tempo analysis\" . Suggest cut points at beat markers. Auto-sync all performance takes to master audio. 1.5 Social Media (Short-F orm) Pacing Philosophy : Attention is currency. Earn it every second. \u2022 The Hook : Frame 1 must contain a face,",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk4",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 4,
    "content": "nc all performance takes to master audio. 1.5 Social Media (Short-F orm) Pacing Philosophy : Attention is currency. Earn it every second. \u2022 The Hook : Frame 1 must contain a face, product, or text. No establishing shots in the first 2 seconds. \u2022 T ext-on-Screen: Every 3-5 seconds, add contextual text or emoji to reinforce the message (85% watch without sound). Text should be 6-8 words max, 4% frame height, bold sans-serif. \u2022 Pattern Interrupt : Change camera angle, zoom level, or add a graphic every 2-3 seconds to prevent scroll-past behavior. \u2022 V ertical F raming: For 9:16, keep subjects in the upper 60% of frame (phone thumb zone covers bottom 40%). Never put critical info in the bottom 15%. \u2022 Captions: Burn in captions with high contrast (white text, black outline or background bar). Use 2-line max, 32 chars per line. \u2022 Prometheus Default : Enable \"social hook detection\" - flag best opening frames. Auto-suggest text overlays at 3-second intervals. Apply smart_reframe with subject tracking in upper 60%. 1.6 Corporate / Educational Pacing Philosophy : Clarity over creativity. Information retention is the goal. \u2022 The 7-Minute Rule : Attention drops significantly after 7 minutes. For longer content, insert chapter markers or visual breaks every 5-7 minutes. Generated by Kimi.ai \u2022 Lower Thirds : Identify speakers with lower thirds for first 5 seconds of appearance. Font: clean sans-serif, 3% frame height, left-aligned with 8%",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk5",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 5,
    "content": "minutes. Generated by Kimi.ai \u2022 Lower Thirds : Identify speakers with lower thirds for first 5 seconds of appearance. Font: clean sans-serif, 3% frame height, left-aligned with 8% safe margin. \u2022 Screen Recording : When showing software/interface, add cursor highlights and zoom-in on click targets. Hold on completed actions for 2 seconds. \u2022 Data Visualization : Animate charts/graphs rather than showing static images. Use 1-second build-in animations. \u2022 Prometheus Default : Enable auto-transcription for searchable content. Suggest chapter markers at topic transitions. Auto-generate lower thirds from speaker metadata. 1.7 Live Event / Sports Pacing Philosophy : Energy preservation. The edit should feel like being there. \u2022 Multi-Cam Rules : Never stay on the same camera >10 seconds. Cut on action (goal, applause, speaker gesture). Use crowd reactions as emotional bridge between plays. \u2022 Instant Replay : Show real-time play (3-5 seconds), then slow-motion replay (25% speed) with graphic overlay (circle/highlight on key action). Return to live at 2x speed ramp. \u2022 Audio Bed : Maintain ambient crowd noise at -20dB under commentary to preserve atmosphere. Never fully mute crowd. \u2022 Highlight Extraction : Key moments = goals, saves, fouls, celebrations, crowd close-ups, coach reactions. Sequence: Wide shot -> Tight action -> Celebration -> Crowd -> Replay. \u2022 Prometheus Default : Enable \"event detection\" (applause, cheer, whistle).",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk6",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 6,
    "content": "rowd close-ups, coach reactions. Sequence: Wide shot -> Tight action -> Celebration -> Crowd -> Replay. \u2022 Prometheus Default : Enable \"event detection\" (applause, cheer, whistle). Auto-generate highlight reel with 30/60/120-second options. Apply crowd noise bed under all cuts. 2. ADV ANCED CREATIVE TECHNIQUES 2.1 The Match Cut A cut where visual elements align across two shots, creating seamless transition. \u2022 Shape Match : Circular object in shot A -> circular object in shot B \u2022 Color Match : Red object in shot A -> red object in shot B \u2022 Motion Match : Pan right in shot A -> pan right in shot B \u2022 T exture Match: Water ripples -> fabric waves Prometheus Implementation : Use visual analysis to detect shapes, colors, and motion vectors. Suggest match-cut candidates between scenes with similarity score >0.75. 2.2 The Smash Cut Abrupt cut from quiet/serene to loud/chaotic (or vice versa) for comedic or dramatic impact. \u2022 Audio Requirement : Minimum 12dB level difference between pre-cut and post-cut audio \u2022 Visual Requirement : Maximum contrast in visual energy (static -> motion, or bright -> dark) Generated by Kimi.ai \u2022 Duration: Post-cut shot should be 1-2 seconds maximum for comedic effect; 3-5 seconds for horror/ drama Prometheus Implementation : Flag moments with high audio/visual contrast within 5second windows. Suggest smash-cut placement with confidence score. 2.3 The Invisible Split-Screen Two shots filmed at different",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk7",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 7,
    "content": "lag moments with high audio/visual contrast within 5second windows. Suggest smash-cut placement with confidence score. 2.3 The Invisible Split-Screen Two shots filmed at different times/locations but composited to look like continuous space. \u2022 Requirements: Matching lighting direction, color temperature, camera height, and lens focal length \u2022 Common Use : Dialogue scenes with actors who weren't on set together, or \"twin\" performances \u2022 Edge T reatment: Feather split line by 20-50 pixels. Add subtle motion blur or film grain to unify. Prometheus Implementation : Flag clips with matching lighting/color profiles as split-screen candidates. Suggest feather width based on focal length. 2.4 Time Remapping & Speed Ramps Variable speed within a single clip for dramatic effect. \u2022 Build-Up: 100% -> 150% -> 200% -> freeze frame (0%) -> impact at 25% -> resume 100% \u2022 Flashback: 100% -> 50% with desaturation -> 25% with heavy grain -> dissolve to present \u2022 Comedy: 100% -> 10% on reaction face -> hold for 2 seconds -> snap to 100% Prometheus Implementation: Detect motion peaks, facial expressions, and audio impacts as ramp trigger points. Suggest ramp curves (linear, ease-in, ease-out, exponential). 2.5 The Montage Sequence Compressed time showing progression or repetition. \u2022 Shot Duration Progression : Start with 2-second shots, progressively shorten to 0.5 seconds to build energy \u2022 Audio Bridge : Single music track or voiceover bridges",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk8",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 8,
    "content": "repetition. \u2022 Shot Duration Progression : Start with 2-second shots, progressively shorten to 0.5 seconds to build energy \u2022 Audio Bridge : Single music track or voiceover bridges all cuts. Never use diegetic sound in montage unless for comedic effect. \u2022 Visual Motif : Repeating visual element (clock, calendar, same action at different times) creates cohesion \u2022 J-Cut/L-Cut Heavy : Audio from next shot begins 6-12 frames early to smooth rapid cutting Prometheus Implementation : Auto-detect repetitive actions or time-lapse sequences. Suggest montage assembly with progressive duration curve. 3. MUSIC & SOUND DESIGN INTEGRATION 3.1 Music Selection Criteria Prometheus scores music candidates on: 1. T empo Match: BPM within \u00b15% of target pace (weight: 30%) 2. Mood Alignment : Emotional valence matches scene tone (weight: 30%) Generated by Kimi.ai 3. Energy Curve : Music dynamics match visual pacing (build, drop, sustain) (weight: 20%) 4. Duration Fit : Track length within 20% of target sequence length (weight: 15%) 5. Licensing: License type matches project budget (weight: 5%) 3.2 Sound Design Layers Every professional edit contains 4 audio layers: 1. Dialogue/V oice: Primary narrative audio, always in mono or centered stereo 2. Music: Emotional bed, stereo or surround, ducked under dialogue 3. Ambient/Background: Location atmosphere (room tone, city, nature), subtle but present 4. Sound Effects (SFX) : Spot effects (door closes,",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk9",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 9,
    "content": "reo or surround, ducked under dialogue 3. Ambient/Background: Location atmosphere (room tone, city, nature), subtle but present 4. Sound Effects (SFX) : Spot effects (door closes, footsteps, UI sounds), panned to match screen position Prometheus Rule: Never deliver with silent backgrounds. If location audio lacks ambient, generate room tone from cleanest section and loop at -30dB. 3.3 The LUFS Ladder (Layered Loudness) \u2022 Dialogue: -23 LUFS (anchor) \u2022 Music: -35 LUFS when dialogue present, -23 LUFS when solo \u2022 Ambient: -40 LUFS (barely perceptible but present) \u2022 SFX: -20 to -30 LUFS depending on prominence Prometheus Implementation: Auto-duck music using sidechain compression triggered by dialogue. Maintain ambient bed at all times. Flag SFX that exceed dialogue by >6dB. 4. PLATFORM-SPECIFIC CREATIVE CONSTRAINTS 4.1 Y ouT ube \u2022 Thumbnail F rame: Extract at 30% of video duration (typically after hook, before main content). Frame must contain face, high contrast, and readable text if any. \u2022 End Screen : Last 20 seconds reserved for end screen elements (subscribe button, related videos). Keep main content out of this zone. \u2022 Chapters: Add at natural topic breaks. Chapter titles: 3-5 words, front-loaded with keywords. \u2022 Cards: Suggest card placement at moments of high engagement (not during dialogue - use during B-roll or transitions). 4.2 Instagram / F acebook \u2022 Safe Zones : Keep text and critical subjects within center 80% (20%",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk10",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 10,
    "content": "oments of high engagement (not during dialogue - use during B-roll or transitions). 4.2 Instagram / F acebook \u2022 Safe Zones : Keep text and critical subjects within center 80% (20% margin on all sides) for feed posts. For Reels/Stories, keep in upper 60%. \u2022 Captions: Auto-burn captions. 85% of users watch without sound. Use high-contrast text with background bar. \u2022 Loop A wareness: Last frame should visually connect to first frame for seamless loop (subtle, not jarring). \u2022 Duration: Feed = 15-60 seconds optimal. Reels = 15-30 seconds optimal for completion rate. Generated by Kimi.ai 4.3 TikT ok \u2022 Hook Density : First 1 second must contain motion or face. No static logos or title cards. \u2022 T rending Audio: Use trending sounds when possible for algorithmic boost. Prometheus can detect audio fingerprint matches to trending library. \u2022 T ext Timing: Text should appear for 2-3 seconds minimum. Use \"progressive reveal\" (one line at a time) for storytelling. \u2022 Pattern Interrupt : Change visual every 1.5-2 seconds minimum. Use zooms, cuts, or graphic overlays. 4.4 LinkedIn \u2022 Professional T one: A void flashy transitions. Use clean cuts and subtle dissolves. \u2022 T ext-Heavy: Lower thirds and on-screen quotes perform well. Keep text on screen for 4-5 seconds (professional reading pace). \u2022 Aspect Ratio : 1:1 square performs best in feed. 16:9 for articles/native video. \u2022 Audio: Many watch in o\ufb00ices - burned captions are essential. Keep music",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk11",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 11,
    "content": "ssional reading pace). \u2022 Aspect Ratio : 1:1 square performs best in feed. 16:9 for articles/native video. \u2022 Audio: Many watch in o\ufb00ices - burned captions are essential. Keep music subtle or absent. 4.5 Broadcast / TV \u2022 Safe Margins : Keep all critical content within 90% center (5% margin) for overscan. Text within 80% center. \u2022 Color Gamut : No saturated colors outside broadcast safe (RGB 16-235). Flag super-white and super-black. \u2022 Audio Peaks : Never exceed -1 dBTP. Use true peak limiting, not sample peak. \u2022 Closed Captions : CEA-608/708 or OP-47 teletext compliance required. Position captions in lower-third safe area. \u2022 Duration: Exact frame count matters. 30-second spot = 29:29 at 29.97fps (drop-frame), not 30:00. 5. AI-ASSISTED CREATIVE DECISIONS 5.1 When to Accept AI Suggestions \u2022 T echnical Corrections: Always accept sync, level, color matching, and format compliance suggestions. These are objective. \u2022 Assembly Cuts : Accept as starting point, then refine. AI assembly is 70-80% accurate for interview/documentary, 50-60% for narrative. \u2022 B-Roll Insertion : Review each suggestion. AI may miss emotional nuance or insert irrelevant footage based on keyword matching alone. \u2022 Music Suggestions : Use as discovery tool, not final decision. Music is deeply subjective and brand-specific. \u2022 Color Grading : Accept technical LUTs (log->Rec.709), review creative LUTs. AI doesn't understand brand color guidelines or emotional",
    "tags": [
      "creative",
      "workflows"
    ]
  },
  {
    "id": "doc5-chunk12",
    "source": "05_creative_workflows.pdf",
    "title": "05 Creative Workflows",
    "chunkIndex": 12,
    "content": "ic is deeply subjective and brand-specific. \u2022 Color Grading : Accept technical LUTs (log->Rec.709), review creative LUTs. AI doesn't understand brand color guidelines or emotional subtext. 5.2 When to Override AI \u2022 Emotional Beats : AI tends to cut too quickly. Override with longer holds on close-ups during vulnerability, silence, or revelation. Generated by Kimi.ai \u2022 Comedic Timing : AI doesn't understand comedic pause. The space between setup and punchline is sacred - never auto-cut through it. \u2022 Product Reveals: AI may cut away too early from a product hero shot. Hold 1.5 seconds minimum after full reveal. \u2022 Brand Compliance : If AI suggests a transition or color grade that violates brand guidelines, override immediately and flag the rule for future learning. 5.3 The Human-in-the-Loop Protocol Prometheus operates on a 3-tier approval system: \u2022 Tier 1 (Auto-Execute) : Technical corrections, format conversions, proxy generation, sync - no human approval needed. \u2022 Tier 2 (Suggest-Accept) : Assembly cuts, B-roll insertion, music selection, color matching present to user with 3 options, default to highest confidence. \u2022 Tier 3 (Human Decision) : Final cut approval, creative LUT selection, pacing adjustments, narrative restructuring - AI presents analysis, human decides. END OF CREATIVE WORKFLOWS & GENRE-SPECIFIC EDITING DOCUMENT Generated by Kimi.ai",
    "tags": [
      "creative",
      "workflows"
    ]
  }
] satisfies PrometheusKnowledgeChunk[]
