import type { Metadata } from 'next'

import { LEGAL_LAST_UPDATED, LegalLayout, LegalSection, LegalSubsection } from '@/components/legal/LegalLayout'

export const metadata: Metadata = {
  title: 'Terms of Service | Prometheus',
  description: 'Read the Terms of Service for Prometheus.',
}

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      description="These terms outline the working launch framework for Prometheus and should be finalized with counsel before public release."
      currentPath="/terms"
    >
      <LegalSection title="1. Introduction and Agreement">
        <p>
          These Terms &amp; Conditions constitute a legally binding agreement made between you and Prometheus AI (&apos;Company&apos;, &apos;we&apos;, &apos;us&apos;, or &apos;our&apos;), concerning your access to and use of the prometheusstudio.tech website and services.
        </p>
        <p>
          Welcome to Prometheus AI (&quot;Prometheus&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). These Terms &amp; Conditions
          govern your access to and use of prometheusstudio.tech and our AI-powered cinematic content
          production infrastructure. By accessing or using our services, you agree to be bound by these
          terms.
        </p>
        <p>Last updated: {LEGAL_LAST_UPDATED}</p>
      </LegalSection>

      <LegalSection title="2. Merchant of Record">
        <p>
          Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of
          Record for all our orders. Paddle provides all customer service inquiries and handles returns
          regarding billing and payments. Your relationship regarding the financial transaction is with
          Paddle.com, governed by their standard terms of service.
        </p>
      </LegalSection>

      <LegalSection title="3. Intellectual Property and Content Ownership">
        <LegalSubsection title="Your Inputs">
          <p>
            You retain all ownership rights to the raw footage, audio, text, and assets (&quot;Inputs&quot;) you
            upload to Prometheus. You grant us a limited, worldwide, non-exclusive license to host,
            process, and manipulate your Inputs solely for the purpose of providing our Service to you.
          </p>
        </LegalSubsection>
        <LegalSubsection title="Your Outputs">
          <p>
            Subject to your compliance with these Terms, you own all rights, title, and interest in the
            final rendered videos, motion graphics, and media (&quot;Outputs&quot;) generated by Prometheus based on
            your Inputs.
          </p>
        </LegalSubsection>
        <LegalSubsection title="Our Infrastructure">
          <p>
            We retain all rights to the Prometheus operating system, AI models, rendering architecture,
            GSAP motion systems, and proprietary code.
          </p>
        </LegalSubsection>
      </LegalSection>

      <LegalSection title="4. AI Training Data Policy (The Enterprise Promise)">
        <p>
          We respect the proprietary nature of our clients&apos; content. Prometheus does not use your
          private, uploaded brand Inputs or generated Outputs to train our foundational AI models. Your
          content remains siloed within your workspace environment.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable Use and GPU Abuse">
        <p>Prometheus provides heavy GPU compute resources. You agree not to:</p>
        <ul className="list-disc list-inside">
          <li>
            Generate content that promotes violence, self-harm, illegal acts, or constitutes
            non-consensual deepfakes/NSFW material.
          </li>
          <li>Upload copyrighted material for which you do not hold the rights or licenses.</li>
          <li>
            Attempt to reverse-engineer, scrape, or extract our proprietary AI models, motion
            parameters, or GSAP blueprints.
          </li>
          <li>
            Exploit &quot;unlimited&quot; preview tiers using automated bots or scripts to intentionally drain
            GPU/cloud rendering resources. We reserve the right to throttle or suspend accounts
            exhibiting malicious or highly anomalous compute usage.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="6. AI Disclaimers and Limitations of Liability">
        <p>
          Artificial Intelligence is probabilistic. While Prometheus strives for deterministic,
          high-fidelity outputs, we do not guarantee that Outputs will be entirely free of rendering
          artifacts or AI hallucinations. You are solely responsible for reviewing all Outputs before
          public distribution. Prometheus and Prometheus AI shall not be liable for any
          direct, indirect, or consequential damages (including loss of revenue) arising from the use of
          our rendered media.
        </p>
      </LegalSection>

      <LegalSection title="7. Governing Law">
        <p>
          These terms shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria, without regard to its conflict of law provisions.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
