create extension if not exists vector with schema extensions;

create table if not exists public.motion_knowledge_base (
  id bigint generated by default as identity primary key,
  video_url text not null,
  style_reference text not null,
  editing_breakdown text not null,
  embedding extensions.vector(1536) not null
);

alter table public.motion_knowledge_base enable row level security;

revoke all on table public.motion_knowledge_base from anon, authenticated;

create index if not exists motion_knowledge_base_embedding_hnsw_idx
  on public.motion_knowledge_base
  using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.search_motion_knowledge(
  query_embedding extensions.vector(1536),
  match_threshold double precision,
  match_count integer
)
returns table (
  id bigint,
  video_url text,
  style_reference text,
  editing_breakdown text,
  similarity double precision
)
language sql
stable
set search_path = public, extensions
as $$
  select
    motion_knowledge_base.id,
    motion_knowledge_base.video_url,
    motion_knowledge_base.style_reference,
    motion_knowledge_base.editing_breakdown,
    1 - (motion_knowledge_base.embedding <=> query_embedding) as similarity
  from public.motion_knowledge_base
  where 1 - (motion_knowledge_base.embedding <=> query_embedding) >= match_threshold
  order by motion_knowledge_base.embedding <=> query_embedding
  limit least(match_count, 20);
$$;
